---
project_influxdb_admin_username: admin
project_influxdb_admin_password: PassWord
project_influxdb_database: openhab

project_influxdb_user:
  telegraf:
    user_name: telegraf
    user_password: write_only
    grants:
      - database: "{{ project_influxdb_database }}"
        privilege: WRITE
  grafana:
    user_name: grafana
    user_password: read_only
    grants:
      - database: "{{ project_influxdb_database }}"
        privilege: READ
  openhab:
    user_name: openhab
    user_password: read_only
    grants:
      - database: "{{ project_influxdb_database }}"
        privilege: READ

project_influxdb_users:
  - "{{ project_influxdb_user['telegraf'] }}"
  - "{{ project_influxdb_user['grafana'] }}"
  - "{{ project_influxdb_user['openhab'] }}"

project_grafana_admin_user: admin
project_grafana_admin_password: PassWord
