---
project_influxdb_admin_username: admin
project_influxdb_admin_password: PassWord
project_influxdb_database: mydatabase
project_influxdb_users:
  - user_name: write_only
    user_password: write_only
    grants:
      - database: "{{ project_influxdb_database }}"
        privilege: WRITE
  - user_name: read_only
    user_password: read_only
    grants:
      - database: "{{ project_influxdb_database }}"
        privilege: READ

project_grafana_admin_user: admin
project_grafana_admin_password: PassWord
