---
all:
  hosts:
    hab.i.trombik.org:
      ansible_host: 192.168.1.101
  children:
    openhab:
      hosts:
        hab.i.trombik.org:
    prod_credentials:
      children:
        openhab:
    prod:
      children:
        openhab:
